---
title: "JHU Leaflets and Data Tables"
---

```{r setup, include=FALSE}
package::libraries()

wdset("D:/COVID-project/")

pal <- colorNumeric(c("green", "red"), NULL)

states <- states() 
county <- county()
ny_county <- newyork(county)

pop <- my_read("./read-data/USA/population_2018.csv") %>% 
  rename(state = State) %>% rename(pop = Population)

us_state <- my_read("./read-data/JHU/JHU_us_state.csv") 

state_us <- inner_join(inner_join(us_state, pop), states, by = ("state_name" = "state"))

us <- leaflet_manip(state_us) 
```

## US Map

```{r leaflet}
maps <- leaflet(data = us) %>% addTiles() 

maps %>% 
  addPolygons(color = ~pal(cases), fillOpacity = 1, stroke = FALSE, group = "cases") %>%
  addPolygons(color = ~pal(deaths),fillOpacity = 1, stroke = FALSE, group = "deaths") %>%
  addPolygons(color = ~pal(per_cases), fillOpacity = 1, stroke = FALSE, group = "case %") %>%
  addPolygons(color = ~pal(per_deaths), fillOpacity = 1, stroke = FALSE, group = "death %") %>%
  addLayersControl(baseGroups = c("cases", "case %", "deaths", "death %"))
```

This is an interactive map called a leaflet. I set up overlay groups, you can choose between cases, case percent, deaths, death percent. The color defines the overall value of the group you select. The colors are green and red, with green being low value and red being high value.

See [New York Times Maps](https://kctolli.github.io/COVID-19/ny.html#Maps) for exact values. 

## Data Table

```{r tibblea}
us %>% select(state, cases, deaths, pop, per_cases, per_deaths) %>% 
datatable(caption = 'This Tibble shows COVID-19 data in the states in the USA for yesterday',
          class = 'cell-border stripe', 
          rownames = FALSE, 
          filter = 'top', 
          extensions = 'Buttons',
          options = list(buttons = c('copy', 'csv', 'pdf'), 
                         pageLength = 5, 
                         autoWidth = TRUE, 
                         dom = 'Bfrtip'))
```

<br /><br />

```{r update}
update()
```