---
title: "Our World in Data"
subtitle: "Tibbles"
---

```{r setup, include=FALSE}
pacman::p_load(pacman)
p_load(knitr, tidyverse)
p_load(lubridate, sf, USAboundaries, ggrepel, maps, leaflet, dygraphs, data.table, DT)

opts_chunk$set(echo = TRUE)
options(scipen = 999)
options(warn = -1) 

yesterday <- Sys.Date() - 1

week <- yesterday - 14

my_read <- function(df){read_csv(df) %>% unique() %>% na.omit()}

owid <- my_read("https://github.com/BYUI-COVID/read-data/raw/master/OWID/owid_data.csv") 
ecdc <- my_read("https://github.com/BYUI-COVID/read-data/raw/master/OWID/owid_ecdc.csv") 
```

```{r function}
my_wrangle <- function(df){
  df %>% summarise(total_cases = sum(total_cases), 
            total_deaths = sum(total_deaths), 
            total_tests = sum(total_tests), 
            new_cases = sum(new_cases),
            new_deaths = sum(new_deaths),
            new_tests = sum(new_tests),
            median_age = median(median_age),
            life_expectancy = round(as.numeric(mean(life_expectancy),4)), 
            .groups = "keep")
}
```

```{r wrangling}
world <- owid %>% 
  group_by(date) %>% 
  my_wrangle()

yesterday_world <- world %>% 
  filter(date >= week) 

continent <- owid %>% 
  group_by(continent, date) %>% 
  my_wrangle()

yesterday_continent <- continent %>% 
  filter(date >= week) 
```

## Continents

```{r tibblea}
yesterday_continent %>% 
  select(- total_cases, - total_deaths, - total_tests, - life_expectancy) %>% 
datatable(caption = 'This Tibble shows COVID-19 new data for the last 2 weeks',
          class = 'cell-border stripe', 
          rownames = FALSE, 
          filter = 'top', 
          extensions = 'Buttons',
          options = list(buttons = c('copy', 'csv', 'pdf'), 
                         pageLength = 5, 
                         autoWidth = TRUE, 
                         dom = 'Bfrtip'))

yesterday_continent %>% 
  select(- new_cases, - new_deaths, - new_tests, -median_age) %>% 
datatable(caption = 'This Tibble shows COVID-19 total data for the last 2 weeks',
          class = 'cell-border stripe', 
          rownames = FALSE, 
          filter = 'top', 
          extensions = 'Buttons',
          options = list(buttons = c('copy', 'csv', 'pdf'), 
                         pageLength = 5, 
                         autoWidth = TRUE, 
                         dom = 'Bfrtip'))

```

## World

```{r tibbleb}
yesterday_world %>% 
  select(- total_cases, - total_deaths, - total_tests, - life_expectancy) %>% 
datatable(caption = 'This Tibble shows COVID-19 new data for the last 2 weeks',
          class = 'cell-border stripe', 
          rownames = FALSE, 
          filter = 'top', 
          extensions = 'Buttons',
          options = list(buttons = c('copy', 'csv', 'pdf'), 
                         pageLength = 5, 
                         autoWidth = TRUE, 
                         dom = 'Bfrtip'))

yesterday_world %>% 
  select(- new_cases, - new_deaths, - new_tests, -median_age) %>% 
datatable(caption = 'This Tibble shows COVID-19 total data for the last 2 weeks',
          class = 'cell-border stripe', 
          rownames = FALSE, 
          filter = 'top', 
          extensions = 'Buttons',
          options = list(buttons = c('copy', 'csv', 'pdf'), 
                         pageLength = 5, 
                         autoWidth = TRUE, 
                         dom = 'Bfrtip'))

```

<br /><br />

```{r update}
print(paste("Last updated:", 
  format(Sys.Date(), "%b %d %Y")))
```