---
title: "Our World in Data"
subtitle: "Relationship with the World"
---

```{r setup, include=FALSE}
pacman::p_load(pacman)
p_load(knitr, tidyverse)
p_load(lubridate, sf, USAboundaries, ggrepel, maps, leaflet, dygraphs, data.table, DT)

opts_chunk$set(echo = TRUE)
options(scipen = 999)
options(warn = -1) 

yesterday <- Sys.Date() - 1

week <- yesterday - 14

my_read <- function(df){read_csv(df) %>% unique() %>% na.omit()}

owid <- my_read("https://github.com/BYUI-COVID/read-data/raw/master/OWID/owid_data.csv") 
ecdc <- my_read("https://github.com/BYUI-COVID/read-data/raw/master/OWID/owid_ecdc.csv") 
```

```{r function}
my_wrangle <- function(df){
  df %>% summarise(total_cases = sum(total_cases), 
            total_deaths = sum(total_deaths), 
            total_tests = sum(total_tests), 
            new_cases = sum(new_cases),
            new_deaths = sum(new_deaths),
            new_tests = sum(new_tests),
            median_age = median(median_age),
            life_expectancy = round(as.numeric(mean(life_expectancy),4)), 
            .groups = "keep")
}
```

```{r wrangling}
world <- owid %>% 
  group_by(date) %>% 
  my_wrangle()

yesterday_world <- world %>% 
  filter(date >= week) 
```

## Cases

```{r casesa}
ggplot(data = world, aes(x = date, y = total_cases/1000000, color = world)) +
  geom_line() + theme_bw()
```

```{r casesb}
ggplot(data = world, aes(x = world, y = total_cases/1000000)) +
  geom_col() + theme_bw()
```

```{r casesc}
ggplot(data = world, aes(x = date, y = new_cases/1000, color = world)) +
  geom_line() + theme_bw()
```

## Deaths

```{r deathsa}
ggplot(data = world, aes(x = date, y = total_deaths/1000, color = world)) +
  geom_line() + theme_bw()
```

```{r deathsb}
ggplot(data = world, aes(x = world, y = total_deaths/1000)) +
  geom_col() + theme_bw()
```

```{r deathsc}
ggplot(data = world, aes(x = date, y = new_deaths, color = world)) +
  geom_line() + theme_bw()
```

## Tests

```{r testsa}
ggplot(data = world, aes(x = date, y = total_tests/1000000, color = world)) +
  geom_line() + theme_bw()
```

```{r testsb}
ggplot(data = world, aes(x = world, y = total_tests/1000000)) +
  geom_col() + theme_bw()
```

```{r testsc}
ggplot(data = world, aes(x = date, y = new_tests, color = world)) +
  geom_line() + theme_bw()
```

<br /><br />

```{r update}
print(paste("Last updated:", 
  format(Sys.Date(), "%b %d %Y")))
```