---
title: "Project Proposal"
---

```{r load_libraries, include=FALSE}
package::libraries()
```

## Purpose

<!--
* What problem or need will your project address? 
* What will your project do to solve the problem or fulfill the need? 
  + (This should be a brief project description.) 
* What has been done in the past by others to solve the problem or fulfill the need? 
* Why is your project a better solution than what already exists? 
* What is your major and how is your proposed project related to it?
-->

I am a Software Engineering Major, additionally I am getting a Data Science certificate. So this project is a data science type project and will include software design and development. I will address the problem of unclear data on COVID-19. Many people see the data and can't make sense of it. I will also figure how much of the population has been tested. I will compare the techniques used to fight COVID-19, methods may include comparing the countries' data due to each using different methods to control the spread. I will also compare COVID-19 to other viruses to see how the spread of other diseases is affected by the COVID-19 precautions. 

## Methods and Procedures

<!--
* How are you going to complete the project? 
* What are the tasks involved? 
  + Be specific. 
  + "Write the software" is too vague. 
* What research will you have to do? 
* What resources will be required? 
* What is your test plan to make sure it works?
-->

I will find the data sets I will use for this project. The data wrangling and visualization will be done in R. The data analytics will be presented in a github hosted website. I will us Rmd with R-chunks, and YML file to organize my data. I would use many R packages, including knitr, tidyverse, leaflet, sf (simple figures), dygraphs, etc. I will have many plots to test the same visualization.  

--- Data Wrangling and Visualization is [CS/MATH 335](https://byuistats.github.io/M335/index.html)      
&emsp; This project will build on the knowledge gained from that class 

## Work Schedule

<!--
* The overall project should take at least 100 hours to complete. 
* It will consist of the tasks you described in Methods and Procedures. 
* State how long each task will take to complete. 
  + If a task will take longer than five or ten hours, break it up into smaller tasks. 
* Create a calendar or milestone chart that shows which tasks will be completed each week. 
* You will submit a short progress report every two weeks that describes what tasks were accomplished.
-->

Below I have divided the tasks in three-week interval which a line progress reports. 

&emsp; I will use [clockify](https://clockify.me/) to track hours. 

### Whole Semester

Throughout the semester I will spend time gaining knowledge on the follow as it relates to my project:  

&emsp; (Notes and Resources will be posted in the organizations github repos)

* Ethics in Data
* Consulting in Statistics and Data Science
* Rstudio Connect
* Analysis - Poor, [Good, Better, Best](https://www.churchofjesuschrist.org/study/general-conference/2007/10/good-better-best?lang=eng)
* R packages
* Making Inferences with Data
* and more

### Progress Report 1 (Due 5/9)

* Start Project
  + Proposal
* Do some data research
* Find data sets to work with
  + Such as [JHUs github](https://github.com/CSSEGISandData/COVID-19)
  + Or [CDC](https://www.cdc.gov/flu/weekly/weeklyarchives2019-2020/data/whoAllregt_phl15.html) flu data
* Create github organization
* Host the website in main repo

### Progress Report 2 (Due 5/30)

* Load in the data sets
  + Look through the data set
* Start wrangling
* Make basic visualizations to see the data
* Develop YML file 

### Progress Report 3 (Due 6/20)

* Wrangle and Visualize data
  + Non-interactive plots
  + Interactive plots
* Learn more about the 
  + [ggplot](https://www.rdocumentation.org/packages/ggplot2/versions/3.3.0)
  + [sf plots](https://r-spatial.github.io/sf/articles/sf1.html)
  + [leaflet](https://leafletjs.com/)
  + [dygraphs](https://rstudio.github.io/dygraphs/)
  + other plot tools

### Progress Report 4 (Due 7/11)

* Last steps website
  + Finalize visualizations 
  + Finalize YML
  + Finalize tibbles
* Start report

### Final Delivery (Due 7/22)

* Finish data presentation website
* Peer reviewed 
  + Make edits/modifications
* Complete report

## Results

<!--
* What are the expected outcomes?
-->

My expected outcomes are using data visualizations and documentation will be shown on a github website. I will have leaflets, dygraphs, ggplots and more visualizations, to describe the data. The results will be shown using Rmd files that will be put through knitr to get html and Yml files will create the headers and javascript. This website will help people understand the data of COVID-19 and other viruses using data visualizations. As people are aware and understand they can take appropriate actions. With the data visualization I would be able see what controlling method is best when dealing with COVID-19. 

<br /> <br />

--- Knowledge for this project is pulled from [CSE 150, CS 225, 241, 335, Math 221, 325, 330, 425, 488, 498, and 499](https://byuistats.github.io/).   