---
title: "Data"
---

```{r load_libraries, include=FALSE}
library(tidyverse)
library(knitr)
```

## Sources

I found three useful dataset hosts; they are NYTimes, Our World in Data and JHU CSSEGIS. 

* Nytimes' github is [nytimes/covid-19-data](https://github.com/nytimes/covid-19-data/). 
* JHU CSSEGIS' github is [CSSEGISandData/COVID-19](https://github.com/CSSEGISandData/COVID-19/). 
* Our World in Data's github is [owid/covid-19-data](https://github.com/owid/covid-19-data)

I also use USAboundaries R package which give state geometry and populations

* The R packages github is [ropensci/USAboundariesData](https://github.com/ropensci/USAboundariesData)
* The R packages reference is [rOpenSci: The USAboundariesData package](https://docs.ropensci.org/USAboundariesData/)

<br /> <br />

## References

CSSEGISandData. (2020). CSSEGISandData/COVID-19. Retrieved 2020,              
&emsp; &emsp; from https://github.com/CSSEGISandData/COVID-19

Nytimes. (2020). Nytimes/covid-19-data. Retrieved 2020,           
&emsp; &emsp; from https://github.com/nytimes/covid-19-data

Owid. (2020). Owid/covid-19-data. Retrieved 2020,               
&emsp; &emsp; from https://github.com/owid/covid-19-data

## Package References 

Datasets for the USAboundaries package. (n.d.). Retrieved 2020,               
&emsp; &emsp; from https://docs.ropensci.org/USAboundariesData/

Ropensci. (n.d.). Ropensci/USAboundariesData. Retrieved 2020,               
&emsp; &emsp; from https://github.com/ropensci/USAboundariesData